### ISSUE TITLE
⚙ Update `.github`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-plugin-openreachtech#130]
## Overview

* Update `.github`

## Tasks

- [x] Remove `.github/pull_request_template.md`
- [x] Update `on.pull_request.branches` in `.github/workflows/test-as-development.yml`
- [x] Update Node version to `16.x` in `.github/workflows/test-as-development.yml`
- [x] Add `NODE_AUTH_TOKEN` in `.github/workflows/test-as-development.yml`
