### ISSUE TITLE
🐛 Fix `indent-in-infix-expression`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-plugin-openreachtech#145]
## Overview

* Fix fixing of `indent-in-infix-expression`

## Report

* Linted Code

```
      const isLeadingNode = node.parent?.type !== node.type
        && (
          node.parent?.type === 'Program'
          || node.parent?.loc.start.line !== node.loc.start.line
        )
```

* After `--fix`

```
      const isLeadingNode = node.parent?.type !== node.type
        && (
          node.parent?.type === 'Program'
        || node.parent?.loc.start.line !== node.loc.start.line
        )
```

## Tasks

- [x] Add test for `indent-in-infix-expression` to check
- [x] Add test for `indent-in-infix-expression` to fix
- [x] Fix `indent-in-infix-expression`
