### ISSUE TITLE
🚀 Publish `1.0.0`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-plugin-openreachtech#181]
## Overview

* Publish version as `1.0.0`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #182
- [x] Publish.
- [x] #184
- [x] Push version tag `1.0.0` on main

## npm login to GitHub Packages before publishing

* Procedure login as follows:
  1. get login password from your GitHub settings<br>Go to → https://github.com/settings/tokens
  2. copy your `personal access token` created
  3. run in terminal
      ```
      % npm login --registry=https://npm.pkg.github.com/

      Username: your-github-account-in-lower-case-only
      Password:
      Email: your.mail.account@gmail.com
      Logged in as [your-name] on https://npm.pkg.github.com/.
      ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `770a243`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm login user

  ```
  npm whoami
  ```

- [x] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run
  npm notice 
  npm notice 📦  eslint-plugin-openreachtech@1.0.0
  npm notice === Tarball Contents === 
  npm notice 1.1kB LICENSE                                               
  npm notice 2.4kB README.md                                             
  npm notice 64B   index.js                                              
  npm notice 397B  lib/_.js                                              
  npm notice 6.7kB lib/empty-line-after-super.js                         
  npm notice 2.2kB lib/indent-in-infix-expression.js                     
  npm notice 6.1kB lib/indent-in-infix-expression/IndentValidator.js     
  npm notice 1.3kB lib/newline-per-parameter.js                          
  npm notice 1.7kB lib/newline-per-parameter/ParameterNewlineValidator.js
  npm notice 2.4kB lib/no-comment-in-expression.js                       
  npm notice 1.1kB lib/no-else-if.js                                     
  npm notice 1.9kB lib/no-if-in-oneline.js                               
  npm notice 1.8kB lib/no-unexpected-multiline.js                        
  npm notice 2.9kB lib/no-unexpected-multiline/LineBreakValidator.js     
  npm notice 976B  package.json                                          
  npm notice === Tarball Details === 
  npm notice name:          eslint-plugin-openreachtech             
  npm notice version:       1.0.0                                   
  npm notice filename:      eslint-plugin-openreachtech-1.0.0.tgz   
  npm notice package size:  7.3 kB                                  
  npm notice unpacked size: 33.1 kB                                 
  npm notice shasum:        4ea3192be5afbe6943fbdb36b841eee1bc2d6989
  npm notice integrity:     sha512-clQVTilmVbt7R[...]jpNzuH+P1Fr7w==
  npm notice total files:   15                                      
  npm notice 
  npm notice Publishing to https://registry.npmjs.org/ (dry-run)
  + eslint-plugin-openreachtech@1.0.0
  ```

- [x] Check log of `--dry-run` by other member before actual publishing.
- [ ] `npm publish`

**Comment by EG-easy** [comment]
@StewEucen 

Here is my result of `npm publish --dry-run`.

```sh
$ npm publish --dry-run
npm notice 
npm notice 📦  eslint-plugin-openreachtech@1.0.0
npm notice === Tarball Contents ===
npm notice 1.1kB LICENSE
npm notice 2.4kB README.md
npm notice 64B   index.js
npm notice 397B  lib/_.js
npm notice 6.7kB lib/empty-line-after-super.js
npm notice 2.2kB lib/indent-in-infix-expression.js
npm notice 6.1kB lib/indent-in-infix-expression/IndentValidator.js
npm notice 1.3kB lib/newline-per-parameter.js
npm notice 1.7kB lib/newline-per-parameter/ParameterNewlineValidator.js
npm notice 2.4kB lib/no-comment-in-expression.js
npm notice 1.1kB lib/no-else-if.js
npm notice 1.9kB lib/no-if-in-oneline.js
npm notice 1.8kB lib/no-unexpected-multiline.js
npm notice 2.9kB lib/no-unexpected-multiline/LineBreakValidator.js
npm notice 976B  package.json
npm notice === Tarball Details ===
npm notice name:          eslint-plugin-openreachtech
npm notice version:       1.0.0
npm notice filename:      eslint-plugin-openreachtech-1.0.0.tgz
npm notice package size:  7.3 kB
npm notice unpacked size: 33.1 kB
npm notice shasum:        4ea3192be5afbe6943fbdb36b841eee1bc2d6989
npm notice integrity:     sha512-clQVTilmVbt7R[...]jpNzuH+P1Fr7w==
npm notice total files:   15
npm notice
+ eslint-plugin-openreachtech@1.0.0
```

**Comment by StewEucen** [comment]
* Published
https://www.npmjs.com/package/eslint-plugin-openreachtech
