### ISSUE TITLE
[OSS] Prepare to publish as OSS

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-plugin-openreachtech#24]
## Overview

* Prepare to publish this repository as OSS.
    > このリポジトリを OSS として公開する準備を進める。
    
## Tasks

- [x] Fulfill the missing descriptions in the README.
    > README で不足している記述を埋める。
- [x] Tidy up the English expressions in the README.
    > README の英語表現を仕上げる。
- [x] Change status to public.

**Comment by StewEucen** [comment]
* 此の前公開したので、閉じます🍵
