### ISSUE TITLE
[OSS] Write the background of the creation

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-plugin-openreachtech#25]
## Overview

* Write the background of the creation for each rule.

* See https://github.com/github/eslint-plugin-github/tree/main/docs/rules

## Tasks

* Write about each rule.
- [x] `no-else-if`
  - [x] 日本語
  - [x] In English
- [x] `indent-of-infix-expression`
  - [x] 日本語
  - [x] In English
- [x] `empty-line-after-super`
  - [x] 日本語
  - [x] In English

* Add link to article of each rule in README.md.
- [x] `no-else-if`
- [x] `indent-of-infix-expression`
- [x] `empty-line-after-super`
