### ISSUE TITLE
[Custom-rule] Implement `no-if-in-oneline`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-plugin-openreachtech#28]
## Overview

* Create a rule to forbid `if` statements to be written on a single line.
    > if 文を一行で記述するのを禁止するルールを作成する。
    
* Sample
```
if (conditon) return
if (condition) { return }
```

* See:
[How to Create ESLint Rule](https://github.com/openreachtech/eslint-plugin-openreachtech/wiki/How-to-Create-ESLint-Rule)
[esquery - GitHub](https://github.com/estools/esquery)
    
## Tasks

* 1st period

- [x] Check if there is an ESLint rule to determine this.
    > 此れを判定する ESLint ルールが存在するかどうかを調べる。
- [x] ~If exists, this issue is closed.~
    > ~あったら終了~
    
* 2nd period

- [x] If not, create a custom rule for `eslint-plugin-openreachtech`.
    > 無かったら `eslint-plugin-openreachtech` の custom rule として制作する。
- [x] Create test cases for `no-if-in-oneline`
- [x] Implement `no-if-in-oneline` (without fixer)

* 3rd period

- #85

## After merged

* #65
