### ISSUE TITLE
[Custom-rule] Apply fixer to `indent-in-infix-expression`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-plugin-openreachtech#34]
## Overview

* See https://github.com/openreachtech/eslint-plugin-openreachtech/pull/30#discussion_r841406634

* Example:
https://github.com/eslint/eslint/blob/main/lib/rules/space-infix-ops.js#L83

## Tasks

* 1st period
- [x] Study to write test for ESLint fixer.
- [x] Add test to fixer
- [x] Implement fixer
 
* 2nd period
- [x] ~Update package version~
- [x] ~npm publish~
