### ISSUE TITLE
[Custom-rule] Add test to `IndentValidator`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-plugin-openreachtech#41]
## Overview

* Add test to `IndentValidator`.

## Tasks

* Modify `@private`
- [ ] `#findLeadingNode()`
- [ ] `#isSameLineWithParent()`
- [ ] `#getLeftOperandHeadColumn()`
- [ ] `#getOperatorSpan()`
- [ ] `#getRightOperandHeadColumn()`
- [ ]  `#calculateIndent()`

* Add test
- [ ] Create stub of node of AST.
- [ ] Add test to `#hasShortageIndentBeforeRightOperand()`
- [ ] Add test to `#isNotAlignedBothOperands()`
