### ISSUE TITLE
[OSS] try to install as plugin published with vendor name

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-plugin-openreachtech#50]
## Overview

* Currently, to specify a plugin in the ESLint .eslintrc.yml, we publish our repository on npmjs.com as `eslint-plugin-openreach` without vendor name.
  > 現在、ESLint の .eslintrc.yml 内でプラグインを指定するのに、「ベンダー名の無い `eslint-plugin-openreach`」として当リポジトリを npmjs.com で公開しています。

* However, if we could specify the following to extends in .eslintrc.yml, we could publish it as `@openreachtech/eslint-plugin` with the vendor name.
  > ところが、.eslintrc.yml 内の extends へ以下の様に指定できるとすれば、ベンダー名を付与した `@openreachtech/eslint-plugin` として公開できます。
  
  ```
  {
    "extends": [
      "eslint:recommended",
      "plugin:@typescript-eslint/recommended", // <------------------- like this
      "plugin:react/recommended",
      "prettier"
    ],
    "rules": {
      "react/prop-types": "off",
      "react/react-in-jsx-scope": "off"
    }
  }
  ```
  [うわっ...私の.eslintrc、無駄が多すぎ...？](https://zenn.dev/kimromi/articles/b7cf98005f3193)

## Tasks

* 1st period
- [x] Research that it can clear problem of the vendor name.
["@connehito/eslint-config" をnpmで公開しました](https://tech.connehito.com/entry/2018/04/05/104027)
- [x] If possible, publish to GitHub Packages as `@openreachtech/eslint-plugin`

* 2nd period
- [ ] publish to GitHub Packages with vendor name
- [ ] apply extends in `.eslintrc.yml` of dotfiles repository
- [ ] replace `.eslintrc.yml` in each application and module
