### ISSUE TITLE
[Environment] prepare to release `0.1.0`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-plugin-openreachtech#53]
## Overview

* Prepare to release `0.1.0`

## Release target

* Custom rules:
    - empty-line-after-super
    - index-in-infix-expression

## Tasks

* 1st period

  - [x] add custom rules to `lib/_.js`
  - [x] update package version to `0.1.0`
  - [x] update `package-lock.json` after npm install

* 2nd period

  - [x] #25
  - [x] #56
