### ISSUE TITLE
Create `index.js` file as main of package.json

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-plugin-openreachtech#7]
## Overview

* Create `index.js` to this module main.

## Tasks

- [x] Study ESLint plugin
[Working with Plugins](https://eslint.org/docs/developer-guide/working-with-plugins)
- [x] Report the leaning contens by comments in this issue
- [x] Ceate `index.js`
