### ISSUE TITLE
[obsolete] replace `no-else-if` custom rule with standard rule

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-plugin-openreachtech#77]
## Overview

* Obsolete the custom rule `no-else-if` officially, since it was found to be able to specify in the standard rules.
  > カスタムルールの `no-else-if` が標準ルールで指定可能と分かったので、正式に廃止する。
  
* Keep the source code and documentation for `no-else-if` for posterity to study.
  > `no-else-if` のソースコードとドキュメントは、後学の為に残しておく。

* See https://github.com/openreachtech/eslint-plugin-openreachtech/issues/24#issuecomment-1082111420

## Tasks

* Update ESLint config
  - [x] https://github.com/openreachtech/eslint-config-openreachtech/issues/29

* Obsolete
  - [ ] Add `@deprecated` to `no-else-if`
  - [ ] Remove from README.md with strikethrough

**Comment by StewEucen** [comment]
## 方針

* ESLint の運用で「既存のルールを削除すると後方互換性が損なうので、ルールの廃止は行わない」と云うのがあった。
* 当リポジトリでも踏襲して、`no-else-if` のルールは `no-restricted-syntax` を使わない方法として残して於く。

## 結論

* と云う理由で、此の issue は此処でお仕舞い。
