### ISSUE TITLE
[Brush-up] Fix ESLint types

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-plugin-openreachtech#92]
## Overview

* Fix ESLint types.

* Examples:
```
- /** @type {import('eslint/lib/shared/types').Rule} */
+ /** @type {import('eslint').Rule.RuleModule} */
```

```
  /**
   * Create rule handler.
   * @param {import('./shared/types').RuleContext} context - Rule context.
   * @returns {import('./shared/types').RuleHandler} - Rule handler.
   */

↓

  /**
   * Create rule listener.
   * @param {import('eslint').Rule.RuleContext} context - Rule context.
   * @returns {import('eslint').Rule.RuleListener} - Rule listener.
   */
```

## Tasks

- [x] apply `import('eslint').Rule.RuleModule`
- [x] apply `import('eslint').Rule.RuleContext`
- [x] apply `import('eslint').Rule.RuleListener`
- [x] apply 'import('estree')'
- [x] remove `import('./shared/types')` for ESLint types
