### ISSUE TITLE
🐛  Fix custom rule `newline-per-parameter` with rest parameters (...restParams)

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-plugin-openreachtech#97]
## Overview

* Fix custom rule `newline-per-parameter` with rest parameters (...restParams).

## Tasks

- [x] Add test to one-param
- [x] Add test to two-params
- [x] Add test to three-params
- [x] Fix code
